import { ADDITIONAL_QUESTIONS } from "./question-expansion";

export type SourceMode = "past" | "mock";

export type SubjectId =
  | "mathematics"
  | "computer-science"
  | "physics"
  | "engineering"
  | "materials-science"
  | "chemistry"
  | "biology"
  | "medicine"
  | "economics"
  | "ppe"
  | "law"
  | "english";

export interface Subject {
  id: SubjectId;
  name: string;
  nameEn: string;
  short: string;
  family: "STEM" | "Life Sciences" | "Social Sciences" | "Humanities";
  icon: string;
}

export interface InterviewQuestion {
  id: string;
  subject: SubjectId;
  sourceMode: SourceMode;
  origin: string;
  sourceTitle: string;
  difficulty: "Warm-up" | "Core" | "Stretch";
  question: string;
  questionZh?: string;
  zhGuide: string;
  guideEn?: string;
  anchors: string[];
  hints: [string, string, string];
  hintsEn?: [string, string, string];
  modelAnswer: string;
  modelAnswerZh?: string;
  rubricKeywords: string[];
  followUp: string;
  followUpZh?: string;
  diagram?: DiagramKind;
  sketchPrompt?: string;
  sketchPromptZh?: string;
}

export type DiagramKind =
  | "graph"
  | "circle-rectangle"
  | "velocity-time"
  | "forces"
  | "beam"
  | "energy-profile"
  | "titration"
  | "logistic"
  | "medical-curve"
  | "supply-demand"
  | "argument-map"
  | "balance"
  | "text-structure";

export const SUBJECTS: Subject[] = [
  { id: "mathematics", name: "数学", nameEn: "Mathematics", short: "Maths", family: "STEM", icon: "∑" },
  { id: "computer-science", name: "计算机科学", nameEn: "Computer Science", short: "CS", family: "STEM", icon: "</>" },
  { id: "physics", name: "物理", nameEn: "Physics", short: "Physics", family: "STEM", icon: "λ" },
  { id: "engineering", name: "工程", nameEn: "Engineering", short: "Eng", family: "STEM", icon: "⌁" },
  { id: "materials-science", name: "材料科学", nameEn: "Materials Science", short: "Materials", family: "STEM", icon: "◇" },
  { id: "chemistry", name: "化学", nameEn: "Chemistry", short: "Chem", family: "STEM", icon: "⚗" },
  { id: "biology", name: "生物", nameEn: "Biology", short: "Biology", family: "Life Sciences", icon: "⌘" },
  { id: "medicine", name: "医学与生物医学", nameEn: "Medicine & Biomedical Sciences", short: "Medicine", family: "Life Sciences", icon: "+" },
  { id: "economics", name: "经济与管理", nameEn: "Economics & Management", short: "Econ", family: "Social Sciences", icon: "↗" },
  { id: "ppe", name: "PPE", nameEn: "Philosophy, Politics & Economics", short: "PPE", family: "Social Sciences", icon: "◎" },
  { id: "law", name: "法律", nameEn: "Law", short: "Law", family: "Humanities", icon: "§" },
  { id: "english", name: "英语文学", nameEn: "English Literature", short: "English", family: "Humanities", icon: "¶" },
];

const CORE_QUESTION_BANK: InterviewQuestion[] = [
  {
    id: "math-past-ladder",
    subject: "mathematics",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "A ladder leans against a vertical wall. As it slides to the floor, what curve is traced by its middle rung?",
    zhGuide: "不要凭图形直觉猜测；尝试把梯子长度、端点坐标和中点坐标联系起来。",
    anchors: ["Pythagoras", "Coordinate geometry", "Locus"],
    hints: [
      "把墙角设为原点。若梯子两端坐标为 (x,0) 与 (0,y)，梯长恒定意味着什么？",
      "中点坐标是 (x/2,y/2)。把 x²+y²=L² 改写成中点坐标的关系。",
      "你得到的是 X²+Y²=(L/2)²；再考虑 X、Y 的取值范围，完整轨迹是哪一部分？",
    ],
    modelAnswer: "Let the foot and top of a ladder of length L be at (x,0) and (0,y). Because the ladder length is fixed, x²+y²=L². The midpoint is M=(x/2,y/2). Writing its coordinates as (X,Y), we have x=2X and y=2Y, so 4X²+4Y²=L², or X²+Y²=(L/2)². Since the ladder remains in the first quadrant, the midpoint traces a quarter-circle of radius L/2 centred at the corner. I would also check the endpoints: it begins at (0,L/2) and ends at (L/2,0), which is consistent.",
    rubricKeywords: ["pythagoras", "coordinate", "midpoint", "quarter", "circle", "radius", "locus"],
    followUp: "What path would be traced by a point one third of the way up the ladder?",
  },
  {
    id: "math-past-average-speed",
    subject: "mathematics",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "The Ultimate Oxbridge Collection",
    difficulty: "Warm-up",
    question: "I drive to the interview at speed v along a fixed route. How fast must I drive home for my average speed over both journeys to be 2v?",
    zhGuide: "先质疑题目是否可行。平均速度必须用总路程除以总时间，而不是两个速度的算术平均。",
    anchors: ["Speed-distance-time", "Algebra", "Limits"],
    hints: [
      "设单程距离为 d。去程时间是多少？如果返程速度为 u，返程时间是多少？",
      "写出 2d ÷ (d/v+d/u)=2v，并尝试求 u。",
      "方程会要求 d/u=0。有限速度能让返程时间为零吗？这说明目标平均速度是否可达到？",
    ],
    modelAnswer: "Let each leg have distance d and let the return speed be u. The total time is d/v+d/u, so the average speed is 2d divided by that quantity. Setting it equal to 2v gives 2d/(d/v+d/u)=2v. Cancelling terms implies 1/v+1/u=1/v, hence 1/u=0. That would require an infinite return speed. Therefore no finite speed can produce an average of 2v. The reason is that the outward journey alone already takes d/v, which is the entire time allowance for covering 2d at average speed 2v.",
    rubricKeywords: ["total distance", "total time", "infinite", "impossible", "limit", "harmonic"],
    followUp: "If the target average were 1.5v, what return speed would be required?",
  },
  {
    id: "math-mock-tangent",
    subject: "mathematics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "A tangent to y=x² at x=a meets the x-axis at P. As a varies, what can you say about the relationship between P and a?",
    zhGuide: "从 A-Level 微分和切线方程出发，不需要任何超纲定理。",
    anchors: ["Differentiation", "Tangents", "Algebra"],
    hints: [
      "在 x=a 处，点坐标与梯度分别是什么？",
      "用点斜式写切线：y-a²=2a(x-a)。令 y=0。",
      "当 a≠0 时求出 P 的横坐标；再单独讨论 a=0。",
    ],
    modelAnswer: "At x=a, the point on the curve is (a,a²) and the gradient is 2a. The tangent is therefore y-a²=2a(x-a), or y=2ax-a². Setting y=0 gives x=a/2 when a is non-zero, so P always lies halfway between the origin and the vertical projection of the point of tangency onto the x-axis. When a=0, the tangent is the x-axis itself, so there is no unique intercept. I would separate that case rather than divide by a without checking.",
    rubricKeywords: ["gradient", "differentiate", "tangent", "intercept", "a/2", "special case"],
    followUp: "How would the result change for y=xⁿ?",
  },
  {
    id: "math-mock-random-chord",
    subject: "mathematics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "What does it mean to choose a random chord of a circle, and could different reasonable methods give different probabilities that it is longer than the side of an inscribed equilateral triangle?",
    zhGuide: "重点不是立刻算出数字，而是识别“随机”需要一个明确的生成过程。",
    anchors: ["Probability", "Geometry", "Modelling assumptions"],
    hints: [
      "先提出至少两种生成弦的方法，例如随机选两个圆周点，或随机选弦的中点。",
      "弦长只取决于它的中点到圆心的距离。长于内接等边三角形边长意味着中点距离满足什么条件？",
      "不同方法在圆内对中点的分布并不相同，因此概率模型可能给出不同结果。",
    ],
    modelAnswer: "The phrase random chord is incomplete until a sampling rule is specified. One method is to choose two independent uniform points on the circumference. Another is to choose a random radius direction and then choose the chord midpoint uniformly along that radius; a third is to choose the midpoint uniformly over the disk. A chord is longer than the side of an inscribed equilateral triangle exactly when its midpoint lies within half a radius of the centre. These methods place different probability measures on midpoint distance, so they need not give the same probability. The apparent paradox is therefore a modelling ambiguity, not a contradiction in geometry.",
    rubricKeywords: ["random", "sampling", "method", "midpoint", "probability measure", "assumption", "ambiguity"],
    followUp: "Which sampling method would be most natural in a physical experiment with falling straws?",
  },
  {
    id: "cs-past-pirates",
    subject: "computer-science",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "Seven perfectly logical pirates must divide 100 coins. The most senior proposes; if at least half vote yes, it passes, otherwise the proposer is thrown overboard. What should the most senior propose?",
    zhGuide: "用递归/逆向归纳把七人问题拆成一人、两人、三人……的小问题。",
    anchors: ["Backward induction", "Algorithms", "Logical proof"],
    hints: [
      "从只剩 1 名、2 名、3 名海盗开始，记录每一步谁会得到 0 枚金币。",
      "当前提案者只需收买在下一轮中将得到最少金币的人，并给他们多 1 枚。",
      "七人时需要至少 4 票，包括自己，所以还需买 3 票；优先给下一轮会拿 0 的三人各 1 枚。",
    ],
    modelAnswer: "I would solve the game backwards because each pirate compares the current offer with the outcome after the proposer dies. At every stage, the proposer counts their own vote and buys the cheapest additional votes by offering one coin more than those pirates would receive in the next round. With seven pirates, four votes are required, so the senior pirate needs three allies. In the six-pirate outcome, three pirates receive zero; offering each of those pirates one coin secures their votes. The senior pirate can therefore keep 97 coins and distribute 1,0,1,0,1,0 in the appropriate alternating pattern. The exact identities follow from the backward-induction table.",
    rubricKeywords: ["backward", "induction", "vote", "next round", "one coin", "97", "logical"],
    followUp: "How would the solution change if a strict majority, rather than half, were required?",
  },
  {
    id: "cs-past-lily",
    subject: "computer-science",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "The Ultimate Oxbridge Collection",
    difficulty: "Core",
    question: "A frog starts on pad 0 and can jump forward by one or two pads. How many different ways can it reach pad 10?",
    zhGuide: "不要暴力枚举。把到达第 n 个位置的方法按最后一步分类。",
    anchors: ["Recursion", "Fibonacci sequence", "Dynamic programming"],
    hints: [
      "到达 n 的最后一步只能来自 n-1 或 n-2。",
      "因此 W(n)=W(n-1)+W(n-2)。先确定 W(0) 与 W(1)。",
      "从 W(0)=1、W(1)=1 逐项算到 W(10)，并解释为什么空路径应计为一种方法。",
    ],
    modelAnswer: "Let W(n) be the number of ways to reach pad n. Every valid route ends either with a one-pad jump from n-1 or a two-pad jump from n-2, and these cases do not overlap. Hence W(n)=W(n-1)+W(n-2). Taking W(0)=1 for the empty route and W(1)=1 gives 1,1,2,3,5,8,13,21,34,55,89. Therefore there are 89 ways to reach pad 10. Algorithmically, I would compute this iteratively using only the previous two values, giving O(n) time and O(1) extra space.",
    rubricKeywords: ["recurrence", "n-1", "n-2", "fibonacci", "89", "complexity"],
    followUp: "What recurrence applies if the frog can jump up to three pads?",
  },
  {
    id: "cs-mock-search",
    subject: "computer-science",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "You have one million student records sorted by surname. A surname may occur many times. How would you find every matching record efficiently?",
    zhGuide: "把普通二分查找扩展为寻找重复值的左边界和右边界。",
    anchors: ["Binary search", "Complexity", "Edge cases"],
    hints: [
      "一次二分查找能找到某个匹配项，但不能保证找到第一个。",
      "修改二分判断：即使找到目标，也继续向左寻找最早位置；再对右侧做对称操作。",
      "两次边界查找是 O(log n)，输出 k 条记录本身需要 O(k)，所以总复杂度是什么？",
    ],
    modelAnswer: "I would use two modified binary searches. The first finds the leftmost occurrence: when the middle surname is equal to the target, I store that index but continue searching the left half. The second does the symmetric search for the rightmost occurrence. If no match is found, the result is empty; otherwise every record in the closed interval between those indices matches. The searches take O(log n) time, while returning k records necessarily takes O(k), so the total is O(log n+k). I would also specify a consistent collation rule for case, punctuation and non-Latin names.",
    rubricKeywords: ["binary", "leftmost", "rightmost", "boundary", "log", "k", "collation"],
    followUp: "What changes if the records are distributed across several servers?",
  },
  {
    id: "cs-mock-fair-ai",
    subject: "computer-science",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "An admissions model is equally accurate for two groups but has very different false-negative rates. Is it fair?",
    zhGuide: "先区分总体准确率与混淆矩阵中的不同错误，再说明公平并非单一数学定义。",
    anchors: ["Conditional probability", "Confusion matrices", "Algorithmic fairness"],
    hints: [
      "写出 accuracy、false positive 与 false negative 分别衡量什么。",
      "相同准确率可能由不同错误组合产生；对申请者而言，漏掉合格者的代价是什么？",
      "讨论 equal opportunity、calibration、base rates 与制度目标之间可能的冲突。",
    ],
    modelAnswer: "Equal overall accuracy is not enough to establish fairness because it hides how errors are distributed. If one group has a much higher false-negative rate, qualified members of that group are disproportionately rejected, which conflicts with an equal-opportunity criterion. I would examine the confusion matrices, group base rates, calibration and the costs of each error. However, fairness metrics can conflict: equalised error rates and perfect calibration may be impossible simultaneously when base rates differ. The defensible response is therefore to state the chosen fairness objective, justify it in the admissions context, audit data and thresholds, and preserve meaningful human review.",
    rubricKeywords: ["accuracy", "false negative", "base rate", "equal opportunity", "calibration", "trade-off"],
    followUp: "Would removing the group label from the model solve the problem?",
  },
  {
    id: "physics-past-ball",
    subject: "physics",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "A ball, initially at rest, is pushed upward by a constant force for a fixed time. Sketch its velocity from release until it hits the ground.",
    zhGuide: "分阶段画图：受推阶段、只受重力上升阶段、下落阶段；明确正方向和每段加速度。",
    anchors: ["Newton's laws", "Kinematics", "Velocity-time graphs"],
    hints: [
      "取向上为正。施力期间合力 F-mg 是否恒定？速度图的斜率代表什么？",
      "推力停止后加速度变为 -g，速度继续增加还是开始线性下降？",
      "速度过零对应最高点；随后负速度的绝对值线性增大。落地时图在何处结束？",
    ],
    modelAnswer: "Taking upward as positive, the ball first has constant acceleration a=(F-mg)/m, assuming F>mg, so velocity rises linearly from zero while the force acts. When the push stops, the only force is gravity, so the gradient of the velocity-time graph changes abruptly to -g. Velocity then falls linearly to zero at the highest point and becomes increasingly negative during the descent. The graph ends when the ball reaches the ground. If air resistance is ignored, the final downward speed can be related to the height reached; with drag, the descending curve would no longer be perfectly linear.",
    rubricKeywords: ["stages", "gradient", "acceleration", "force", "gravity", "zero", "negative"],
    followUp: "How would air resistance alter the shape of the descending section?",
  },
  {
    id: "physics-past-ice",
    subject: "physics",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "牛剑18个学科900道面试题",
    difficulty: "Warm-up",
    question: "An ice cube floats in a glass of water. What happens to the water level when the ice melts?",
    zhGuide: "用阿基米德原理比较融化前排开水的质量与融化后生成水的质量。",
    anchors: ["Density", "Archimedes' principle", "Conservation of mass"],
    hints: [
      "漂浮时，浮力等于冰的重量。因此被排开的水有多大质量？",
      "融化不会改变冰的质量；融水所占体积等于质量除以水的密度。",
      "比较融水体积与原先排水体积。再讨论冰里若嵌有石块会怎样。",
    ],
    modelAnswer: "The water level remains unchanged. While floating, the ice displaces a volume of water whose weight equals the weight of the ice. Therefore the displaced water has the same mass as the ice. After melting, the ice becomes exactly that same mass of liquid water, and so occupies exactly the volume that had previously been displaced. This argument relies on Archimedes' principle and conservation of mass rather than on comparing the visible sizes of ice and water. If the cube contained another material, I would reconsider whether that material floats or sinks after release.",
    rubricKeywords: ["archimedes", "displaced", "weight", "mass", "volume", "unchanged"],
    followUp: "What happens if the ice cube contains a dense metal ball that sinks after melting?",
  },
  {
    id: "physics-mock-coffee",
    subject: "physics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "You want your coffee coolest after ten minutes. Should you add cold milk immediately or just before drinking?",
    zhGuide: "把直觉转化为热传递模型：降温速率与咖啡和环境的温差有关。",
    anchors: ["Newton's law of cooling", "Thermal energy", "Modelling"],
    hints: [
      "热损失速率通常随咖啡与室温的温差增大而增大。",
      "早加牛奶会立刻降低温差，从而让后续散热更慢；晚加则让咖啡先以更大温差散热。",
      "在忽略蒸发、杯子热容差异且牛奶温度固定的简化模型中，比较两种路径的最终温度。",
    ],
    modelAnswer: "Under Newton's law of cooling, heat loss is approximately proportional to the temperature difference from the room. If I delay adding milk, the coffee remains hotter for most of the ten minutes and therefore loses heat to the surroundings more quickly. Adding the same cold milk at the end then produces a further temperature drop, so late addition usually gives the cooler final drink in the simplest model. I would state the assumptions: fixed milk amount and temperature, good mixing, no significant evaporation difference and constant room conditions. Evaporative cooling or milk warming outside the cup could modify the result.",
    rubricKeywords: ["temperature difference", "newton", "cooling", "heat loss", "assumption", "late"],
    followUp: "Could you derive a symbolic comparison using an exponential cooling model?",
  },
  {
    id: "physics-mock-straw",
    subject: "physics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "Why can a normal drinking straw work, but a ten-metre vertical straw cannot lift water to your mouth?",
    zhGuide: "吸管并不是嘴把水拉上来，而是降低管内压强后由大气压把水推上来。",
    anchors: ["Pressure", "Hydrostatics", "Force balance"],
    hints: [
      "水柱高度 h 需要压强差 ΔP=ρgh 来支撑。",
      "嘴里能达到的最低绝对压强不能低于近似真空；最大压强差约为一个大气压。",
      "用 h=P_atm/(ρg) 估算理论上限，并说明现实上限更低。",
    ],
    modelAnswer: "Drinking reduces the pressure inside the straw; atmospheric pressure on the drink's surface then pushes the liquid upward. A column of height h requires a pressure difference ρgh. Even a perfect vacuum at the top could provide at most one atmosphere of pressure difference, giving h≈101000/(1000×9.81), about 10.3 metres for water at sea level. A ten-metre straw is therefore near the absolute theoretical limit, and a person cannot create a perfect vacuum. Vapour pressure, leaks and flow resistance reduce the practical height further. The straw does not pull the water; the atmosphere pushes it.",
    rubricKeywords: ["atmospheric", "pressure difference", "rho g h", "vacuum", "10", "limit"],
    followUp: "How would the maximum height change on a high mountain?",
  },
  {
    id: "eng-past-ruler",
    subject: "engineering",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "A ruler rests on one fingertip near each end. What happens as you slowly bring your fingers together, and why?",
    zhGuide: "先预测，再用实验现象修正。核心是力矩导致法向力不同，进而影响摩擦力。",
    anchors: ["Moments", "Friction", "Normal reaction"],
    hints: [
      "哪根手指离重心更近？用竖直力平衡和关于某点取矩比较两侧支持力。",
      "最大静摩擦与法向力成正比。支持力较小的一侧更容易滑动。",
      "滑动会交替发生，系统不断重新分配支持力，最终两指在哪里相遇？",
    ],
    modelAnswer: "The fingers meet beneath the ruler's centre of mass rather than one finger reaching it first and tipping the ruler. At any moment, the finger closer to the centre carries a larger normal reaction, as follows from balancing moments. Its maximum static friction is therefore larger, so the ruler tends to slide over the more distant finger, which carries less load. As that finger moves inward, the force distribution changes and the slipping side can switch. This alternating stick-slip process keeps correcting the asymmetry until both fingers arrive at the centre of mass.",
    rubricKeywords: ["centre of mass", "moment", "normal", "friction", "static", "slide", "balance"],
    followUp: "How would different coefficients of friction on the two fingertips affect the result?",
  },
  {
    id: "eng-past-dam",
    subject: "engineering",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "How would you design a gravity dam to hold back water?",
    zhGuide: "从受力图开始，先考虑倾覆和滑移，再扩展到材料、地基和渗流。",
    anchors: ["Hydrostatic pressure", "Moments", "Stability"],
    hints: [
      "水压 p=ρgh 随深度线性增加，所以合力作用点不在水深中点。",
      "画三角形压力分布，求合力及其力矩；坝体重量提供抗倾覆力矩。",
      "除倾覆外，还要检验底部滑移、地基承载、渗流抬升压力与材料应力。",
    ],
    modelAnswer: "I would begin with a free-body diagram. Hydrostatic pressure increases linearly with depth, so the resultant horizontal force is the area of a triangular pressure diagram and acts one third of the water depth above the base. The dam's weight must provide a sufficiently larger restoring moment about the downstream toe. I would also check sliding by comparing horizontal water force with friction and any shear resistance at the base. A practical design then needs safety factors for uplift from seepage, foundation bearing pressure, cracking, earthquakes, overflow and material durability. This explains why a gravity dam is broadest at its base.",
    rubricKeywords: ["pressure", "depth", "resultant", "moment", "sliding", "uplift", "safety factor"],
    followUp: "Why is a triangular cross-section a sensible first approximation?",
  },
  {
    id: "eng-mock-elevator",
    subject: "engineering",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "How would you design an elevator system for a one-kilometre-tall building?",
    zhGuide: "把问题拆成容量、候梯时间、速度、能耗、安全和人体舒适度等约束。",
    anchors: ["Mechanics", "Energy", "Systems design"],
    hints: [
      "先确定目标：每小时运送人数、可接受等待时间、楼层分布与高峰流向。",
      "单部电梯过高会带来绳索质量、井道占地和等待问题；能否分区并设置空中大堂？",
      "讨论再生制动、气压变化、横向摆动、紧急疏散与冗余控制。",
    ],
    modelAnswer: "I would treat this as a transport-network problem rather than simply making one faster lift. I would estimate peak passenger flow and acceptable waiting time, then divide the building into vertical zones served from sky lobbies, with express lifts feeding local groups. This reduces stops and the mass and length of each suspended system. Double-deck cabins and destination control could increase capacity. I would examine acceleration limits for comfort, pressure changes, rope or linear-motor technology, regenerative braking, shaft area, wind-induced sway, fire-safe refuge floors and redundant power and braking. The design would be tested against both normal peaks and evacuation scenarios.",
    rubricKeywords: ["capacity", "zones", "sky lobby", "acceleration", "energy", "safety", "redundancy"],
    followUp: "Which design variable would you optimise first, and why?",
  },
  {
    id: "eng-mock-bridge",
    subject: "engineering",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "A pedestrian bridge begins to sway when many people walk across it. How would you diagnose and reduce the motion?",
    zhGuide: "把人群看作周期性激励，联系固有频率、共振、阻尼和反馈。",
    anchors: ["Oscillations", "Resonance", "Damping"],
    hints: [
      "先测量振动方向、频率、振幅与人流密度，并与结构固有频率比较。",
      "行人可能会无意识地与桥面同步，使激励形成正反馈。",
      "可改变刚度或质量来移开固有频率，也可增加阻尼器；比较各方案代价。",
    ],
    modelAnswer: "I would instrument the bridge with accelerometers and measure frequency, amplitude, direction and dependence on crowd density. If the dominant forcing frequency is close to a structural natural frequency, resonance is likely; pedestrians may then synchronise with the deck, creating positive feedback. A model should include the coupled crowd-structure interaction rather than treating footfall as fixed. Remedies include increasing stiffness, altering mass to shift the natural frequency, installing tuned mass or viscous dampers, and managing pedestrian density temporarily. I would compare options by acceleration limits, fatigue, added load, maintenance and robustness across different crowd patterns.",
    rubricKeywords: ["frequency", "resonance", "damping", "feedback", "measure", "stiffness", "mass"],
    followUp: "How would you distinguish resonance from an aerodynamic instability?",
  },
  {
    id: "materials-past-balloon",
    subject: "materials-science",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "How hot must the air in a hot-air balloon be to lift an elephant?",
    zhGuide: "先建立浮力平衡，再估算气球体积、象的质量和空气密度；允许合理假设。",
    anchors: ["Ideal gas law", "Density", "Buoyancy"],
    hints: [
      "净升力约为 (ρ_out-ρ_in)Vg，需要至少平衡象和气球的总重量。",
      "同一压强下理想气体密度与绝对温度成反比：ρ_in/ρ_out=T_out/T_in。",
      "先选一个合理球囊体积和载荷质量，再求所需密度差与 T_in；检查温度是否现实。",
    ],
    modelAnswer: "I would first state estimates rather than chase a unique number. Suppose the elephant and basket have mass M and the balloon volume is V. Lift requires (ρout-ρin)Vg≥Mg, so ρin≤ρout-M/V. At roughly equal pressure, the ideal-gas relation gives ρin/ρout≈Tout/Tin, hence Tin≈Toutρout/ρin. For example, with M about 5,000 kg, V about 20,000 m³, ρout about 1.2 kg m⁻³ and Tout 293 K, ρin must be about 0.95 kg m⁻³, giving Tin around 370 K, or roughly 100°C. I would then include envelope mass and a safety margin.",
    rubricKeywords: ["buoyancy", "density", "volume", "ideal gas", "temperature", "estimate", "units"],
    followUp: "Which assumption contributes most uncertainty to your estimate?",
  },
  {
    id: "materials-past-diamond",
    subject: "materials-science",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "牛剑18个学科900道面试题",
    difficulty: "Core",
    question: "Why is diamond hard but graphite soft when both are made only of carbon?",
    zhGuide: "从原子键合和结构方向性解释宏观性能，而不是只复述“同素异形体”。",
    anchors: ["Bonding", "Structure-property relationships", "Allotropes"],
    hints: [
      "比较每个碳原子的成键数与三维/二维网络结构。",
      "金刚石中强共价键贯穿三维；石墨层内强、层间弱。",
      "“硬”指抗局部塑性变形或划伤。石墨层间易滑移如何影响这一性质？",
    ],
    modelAnswer: "Composition alone does not determine properties; atomic arrangement and bonding do. In diamond, each carbon is tetrahedrally bonded to four neighbours in a continuous three-dimensional covalent network. Deforming or scratching it requires many strong covalent bonds to be distorted or broken. In graphite, each carbon is strongly bonded to three neighbours within planar sheets, but adjacent sheets interact much more weakly. Those layers can slide over one another, making graphite soft and useful as a lubricant. The delocalised electrons within the sheets also explain why graphite conducts electricity while diamond is normally an electrical insulator.",
    rubricKeywords: ["covalent", "network", "layers", "weak", "slide", "structure", "property"],
    followUp: "Why can a very hard material still be brittle?",
  },
  {
    id: "materials-mock-pan",
    subject: "materials-science",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "A non-stick pan coating begins to peel after repeated heating. How would you investigate the failure?",
    zhGuide: "按材料失效分析思路：观察、提出机制、设计对照实验，再连接到改进方案。",
    anchors: ["Thermal expansion", "Polymers", "Adhesion"],
    hints: [
      "区分涂层内部的内聚破坏与涂层—基体界面的粘附破坏。",
      "金属与聚合物热膨胀系数不同，反复升降温会产生怎样的循环应力？",
      "设计温度、循环次数、表面处理和涂层厚度的对照实验，并选择显微观察或附着力测试。",
    ],
    modelAnswer: "I would first map where peeling begins and inspect the fracture surface to distinguish cohesive cracking within the polymer from adhesive failure at the metal interface. Repeated heating can create cyclic stress because the coating and substrate have different thermal-expansion coefficients; overheating may also degrade the polymer, while scratches or poor surface preparation create stress concentrators. I would run controlled thermal-cycle tests varying peak temperature, heating rate, coating thickness and surface treatment, then measure adhesion and examine cross-sections microscopically. Improvements might include better roughening or primer chemistry, a graded interlayer, controlled thickness and clearer operating-temperature limits.",
    rubricKeywords: ["adhesion", "cohesive", "thermal expansion", "cycle", "stress", "experiment", "interface"],
    followUp: "How could a graded interface reduce the likelihood of delamination?",
  },
  {
    id: "materials-mock-phone",
    subject: "materials-science",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "Would making a smartphone screen harder necessarily make it less likely to break?",
    zhGuide: "区分硬度、强度、韧性与断裂韧度；材料性能之间常存在权衡。",
    anchors: ["Stress-strain behaviour", "Fracture", "Material selection"],
    hints: [
      "硬度主要描述抗压痕/划伤能力；跌落破裂更接近哪种失效？",
      "高硬度材料可能缺少塑性耗能能力，对缺口和表面裂纹敏感。",
      "考虑玻璃成分、化学强化、残余压应力、涂层与层压结构如何共同设计。",
    ],
    modelAnswer: "No. Hardness measures resistance to local indentation or scratching, whereas drop failure depends strongly on flaw size, stress distribution and fracture toughness. A harder material may be more brittle and less able to absorb energy before a crack propagates. For a screen, I would seek a balanced system: a hard surface for scratch resistance, high fracture toughness or compressive residual stress to suppress crack opening, and a laminated structure that spreads impact and retains fragments. Chemical strengthening can place the glass surface in compression. The best design is therefore a multi-objective optimisation, not simply maximising one material property.",
    rubricKeywords: ["hardness", "toughness", "brittle", "crack", "compression", "trade-off"],
    followUp: "Why does placing the glass surface in compression slow crack growth?",
  },
  {
    id: "chem-past-isomers",
    subject: "chemistry",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "How many different molecules can be made from six carbon atoms and twelve hydrogen atoms?",
    zhGuide: "先算不饱和度，再系统分类，而不是随意画结构；同时说明“不同”是否包含立体异构。",
    anchors: ["Organic structures", "Isomerism", "Bonding"],
    hints: [
      "C₆H₁₂ 相比烷烃 C₆H₁₄ 少两个氢，因此不饱和度是多少？",
      "一度不饱和可来自一个环或一个双键。分别按碳骨架系统分类。",
      "最后讨论几何异构、手性与构象是否应计为不同分子；题目定义会影响答案。",
    ],
    modelAnswer: "The formula C₆H₁₂ has one degree of unsaturation, so a structure can contain either one C=C bond or one ring, assuming ordinary closed-shell carbon chemistry. I would count systematically rather than guess: first enumerate distinct carbon skeletons for acyclic alkenes and place the double bond in non-equivalent positions; then enumerate cycloalkanes by ring size and substituent pattern. After removing duplicates caused by symmetry, I would ask whether E/Z and optical stereoisomers count separately, while conformers normally would not. The key is that the numerical answer depends on the definition of different molecule, so I would make that convention explicit before finalising the count.",
    rubricKeywords: ["degree of unsaturation", "alkene", "ring", "symmetry", "stereoisomer", "systematic"],
    followUp: "How would isotopic substitution change what we mean by distinct molecules?",
  },
  {
    id: "chem-past-glycine",
    subject: "chemistry",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "牛剑18个学科900道面试题",
    difficulty: "Core",
    question: "Does the molecular structure of glycine change with pH?",
    zhGuide: "识别羧基和氨基的酸碱行为，按低、中、高 pH 分段分析主要形态。",
    anchors: ["Acid-base equilibria", "pH", "Functional groups"],
    hints: [
      "低 pH 表示 H⁺ 浓度高：氨基和羧基分别倾向于怎样质子化？",
      "在中间 pH，glycine 常以 NH₃⁺—CH₂—COO⁻ 两性离子存在。",
      "高 pH 下进一步去质子化；用 pKa 和 Henderson–Hasselbalch 思路说明形态是分布而非突然切换。",
    ],
    modelAnswer: "Yes, its protonation state changes with pH, although the covalent carbon skeleton remains the same. At low pH, glycine is mainly H₃N⁺CH₂COOH and has net charge +1. As pH rises past the carboxyl pKa, the carboxyl group loses a proton and the zwitterion H₃N⁺CH₂COO⁻ dominates, with net charge zero. At still higher pH, above the ammonium pKa, the amino group deprotonates to H₂NCH₂COO⁻, giving net charge -1. In reality these are equilibrating populations, and the pKa values determine their relative proportions.",
    rubricKeywords: ["proton", "carboxyl", "amino", "zwitterion", "pka", "charge", "equilibrium"],
    followUp: "At what pH would glycine have minimum mobility in an electric field?",
  },
  {
    id: "chem-mock-vitamin",
    subject: "chemistry",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "Why might a vitamin dissolve in water while another accumulates in body fat?",
    zhGuide: "从分子结构、极性和分子间作用力推导溶解性，再联系生物后果。",
    anchors: ["Polarity", "Intermolecular forces", "Solubility"],
    hints: [
      "比较能与水形成氢键或离子—偶极作用的官能团数量。",
      "长烃链或大面积非极性结构更容易与脂质环境相容。",
      "由此推演水溶性维生素更易排出，而脂溶性维生素可能储存并积累。",
    ],
    modelAnswer: "Solubility depends on whether interactions formed with the solvent compensate for those broken. A vitamin with several polar or ionisable groups can form hydrogen bonds or ion-dipole interactions with water, making aqueous solvation favourable. A molecule dominated by hydrocarbon rings or chains has weaker interactions with water but mixes more favourably with non-polar lipid environments. This structural distinction helps explain why water-soluble vitamins circulate and are excreted relatively readily, whereas fat-soluble vitamins can be stored in tissues and may accumulate. I would avoid treating the rule as absolute because pH, formulation and specific functional groups also matter.",
    rubricKeywords: ["polar", "hydrogen bond", "non-polar", "lipid", "solubility", "accumulate"],
    followUp: "How could a drug chemist alter a molecule to improve its water solubility?",
  },
  {
    id: "chem-mock-rate",
    subject: "chemistry",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "A reaction doubles in rate when temperature rises by 10°C. Does that mean every molecule moves twice as fast?",
    zhGuide: "区分平均分子速率与超过活化能阈值的分子比例。",
    anchors: ["Kinetics", "Activation energy", "Boltzmann distribution"],
    hints: [
      "分子平均动能与绝对温度有关，速率与温度的关系并不是简单线性。",
      "反应只由能量足够且取向合适的碰撞产生；温度升高会改变能量分布尾部。",
      "用 Arrhenius 方程 k=Ae^(-Ea/RT) 解释为何小幅升温可显著增大 k。",
    ],
    modelAnswer: "No. Molecular speed scales roughly with the square root of absolute temperature, so a 10°C increase near room temperature produces only a small change in typical speed. Reaction rate is much more sensitive because only a fraction of collisions have enough energy to overcome the activation barrier and the correct orientation. Raising temperature shifts and broadens the Boltzmann energy distribution, substantially increasing the high-energy fraction. The Arrhenius equation, k=Ae^(-Ea/RT), captures this exponential sensitivity. Thus the observed doubling concerns the successful reaction rate constant, not every molecule moving at twice its previous speed.",
    rubricKeywords: ["square root", "activation", "boltzmann", "arrhenius", "collision", "exponential"],
    followUp: "Would a catalyst change the temperature sensitivity in the same way?",
  },
  {
    id: "bio-past-biodiversity",
    subject: "biology",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "Why do some habitats support higher biodiversity than others?",
    zhGuide: "先观察相关性，再提出机制；最后说明如何区分物种形成率与灭绝率的解释。",
    anchors: ["Ecology", "Evolution", "Experimental design"],
    hints: [
      "比较雨林和珊瑚礁：能量输入、稳定性、空间异质性和生态位数量有哪些共同点？",
      "高多样性可能来自更快的物种形成、更低的灭绝，或更多物种共存。",
      "提出可检验预测：需要哪些跨地区数据、系统发育信息或操纵实验？",
    ],
    modelAnswer: "High biodiversity could reflect higher speciation, lower extinction or greater coexistence. Warm, productive and historically stable habitats may provide more energy and time for diversification, while complex physical structure creates many niches and reduces direct competition. Interactions such as predation can also prevent one species from dominating. I would not infer mechanism from latitude alone. To test explanations, I would compare matched habitats while measuring productivity, structural complexity and disturbance, use phylogenies and fossils to estimate diversification rates, and run local experiments that alter resources or habitat complexity. The strongest account should make predictions that distinguish these competing mechanisms.",
    rubricKeywords: ["speciation", "extinction", "niche", "productivity", "stability", "test", "data"],
    followUp: "Could very high productivity ever reduce biodiversity?",
  },
  {
    id: "bio-past-stomata",
    subject: "biology",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "牛剑18个学科900道面试题",
    difficulty: "Warm-up",
    question: "Why do many leaves have more stomata on the lower surface than the upper surface?",
    zhGuide: "从气体交换收益与失水代价的权衡出发，并注意这不是所有植物的绝对规则。",
    anchors: ["Gas exchange", "Transpiration", "Adaptation"],
    hints: [
      "气孔开放允许 CO₂ 扩散进入，也让水蒸气扩散出去。",
      "下表面通常更阴凉、风速更低、边界层更稳定，这会如何影响水势梯度和蒸腾？",
      "讨论浮叶植物、针叶或旱生植物作为例外，说明结构取决于环境。",
    ],
    modelAnswer: "Stomata create a trade-off: they admit carbon dioxide for photosynthesis but also allow water vapour to escape. The lower leaf surface is usually shaded, cooler and less exposed to moving air. Its boundary layer is therefore often thicker and more humid, reducing the diffusion gradient for water vapour and limiting transpiration while gas exchange continues. Concentrating stomata there can improve water-use efficiency. It is not a universal rule: floating leaves need stomata on the upper surface, and xerophytes may use sunken stomata or other adaptations. The distribution reflects the leaf's environment and geometry.",
    rubricKeywords: ["carbon dioxide", "water", "transpiration", "lower", "boundary layer", "adaptation"],
    followUp: "How would wind speed affect the advantage of placing stomata underneath?",
  },
  {
    id: "bio-mock-antibiotic",
    subject: "biology",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "Why can stopping an antibiotic course early increase the chance of resistant bacteria becoming common?",
    zhGuide: "用变异、选择压力和繁殖解释，不要说细菌因为“需要”而主动产生抗药性。",
    anchors: ["Natural selection", "Variation", "Population growth"],
    hints: [
      "治疗前菌群中可能已经存在少量由随机突变或基因转移产生的耐药个体。",
      "抗生素杀死敏感菌，改变不同表型的相对生存和繁殖成功。",
      "若治疗过早停止，存活的较耐药个体可在竞争较少的环境中扩增；同时说明现实用药建议要依具体药物和医嘱。",
    ],
    modelAnswer: "Resistance does not arise because bacteria decide to adapt. Variation may already exist through mutation or horizontal gene transfer. Antibiotic exposure removes susceptible cells more effectively, so resistant cells contribute a larger fraction of the surviving population. If treatment ends while viable bacteria remain, those survivors can reproduce in an environment with reduced competition, increasing the frequency of resistance alleles. The exact effect depends on the drug, infection and dosing strategy, so patients should follow clinical guidance rather than a universal slogan. Evolutionarily, the key elements are pre-existing variation, differential survival and inheritance.",
    rubricKeywords: ["variation", "mutation", "selection", "survive", "reproduce", "inherit", "not need"],
    followUp: "Could excessively long antibiotic use also promote resistance?",
  },
  {
    id: "bio-mock-photosynthesis",
    subject: "biology",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "If a plant receives twice as much light, will its rate of photosynthesis double?",
    zhGuide: "用限制因素模型回答，并设计实验区分光照、CO₂ 与温度的影响。",
    anchors: ["Photosynthesis", "Limiting factors", "Graphs"],
    hints: [
      "低光照下光可能是限制因素；随光强增加，曲线通常先怎样变化？",
      "达到平台意味着其他因素限制，例如 CO₂、温度或酶容量。",
      "还要考虑强光造成光抑制。描述一个控制温度和 CO₂ 的测量方案。",
    ],
    modelAnswer: "Only while light is the limiting factor would doubling light approximately double photosynthesis. At low intensity, the light-response curve is often close to linear because more photons drive more photochemistry. As intensity rises, another factor such as carbon dioxide supply, temperature-dependent enzyme activity or chloroplast capacity becomes limiting, so the curve approaches a plateau. At very high intensity, photoinhibition may even reduce the rate. I would test this by varying calibrated light intensity while controlling temperature, carbon dioxide concentration, leaf area and wavelength, then measuring oxygen production or carbon dioxide uptake with repeats and uncertainty estimates.",
    rubricKeywords: ["limiting", "linear", "plateau", "carbon dioxide", "temperature", "photoinhibition", "control"],
    followUp: "How might the shape differ between a shade plant and a sun plant?",
  },
  {
    id: "med-past-glucose",
    subject: "medicine",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "Why is glucose in urine a useful indicator that someone might have diabetes?",
    zhGuide: "连接血糖升高、肾小球滤过、载体重吸收饱和与尿糖。",
    anchors: ["Kidney function", "Transport proteins", "Homeostasis"],
    hints: [
      "葡萄糖会被肾小球滤过，但健康情况下为何尿液中几乎没有？",
      "肾小管重吸收依赖有限数量的载体，存在最大转运速率。",
      "血糖过高使滤过负荷超过重吸收能力，产生尿糖；再说明它为什么不是单独确诊标准。",
    ],
    modelAnswer: "Glucose is small enough to be filtered from blood at the glomerulus, but it is normally reabsorbed in the proximal tubule by transport proteins, so little reaches the final urine. In diabetes, blood glucose may rise enough that the filtered load exceeds the carriers' maximum transport capacity. The transporters become saturated and glucose spills into the urine. This makes glycosuria a useful warning sign, and it can also draw water osmotically into the urine, contributing to frequent urination and thirst. However, renal thresholds vary, so diagnosis should use appropriate blood tests rather than urine glucose alone.",
    rubricKeywords: ["glomerulus", "filter", "reabsorb", "carrier", "saturate", "blood glucose", "osmosis"],
    followUp: "Why might glucose in the tubule increase urine volume?",
  },
  {
    id: "med-past-mortality",
    subject: "medicine",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "Put Bangladesh, Japan, South Africa and the UK in order by crude mortality rate. What information do you need before trusting your answer?",
    zhGuide: "避免把贫穷直接等同于粗死亡率高；注意分母中的人口年龄结构。",
    anchors: ["Epidemiology", "Rates", "Confounding"],
    hints: [
      "粗死亡率是某年死亡人数除以总人口；它没有按年龄标准化。",
      "老龄国家即使医疗好，也可能因为高龄人口比例大而有较高粗死亡率。",
      "比较国家健康状况应考虑年龄标准化率、婴儿死亡率、病因结构与数据质量。",
    ],
    modelAnswer: "I would be cautious about ranking from wealth alone because crude mortality is deaths divided by total population and is strongly affected by age structure. Japan can have a high crude mortality rate despite excellent health outcomes because it has a very old population, while a poorer but younger country can have a lower crude rate. I would therefore request each country's population pyramid, year of measurement and completeness of death registration. For comparing underlying health risk, I would prefer age-standardised mortality and examine cause-specific and infant mortality as well. The central lesson is that a rate can be mathematically correct yet misleading for the comparison being made.",
    rubricKeywords: ["crude", "age structure", "old", "standardised", "population", "confound", "data"],
    followUp: "When would crude mortality still be the appropriate measure to use?",
  },
  {
    id: "med-mock-screening",
    subject: "medicine",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "A new blood test detects a cancer very early but produces many false positives. Should it be used for population screening?",
    zhGuide: "从疾病流行率、敏感度、特异度、阳性预测值以及筛查后的可行动性综合判断。",
    anchors: ["Sensitivity and specificity", "Bayes", "Medical ethics"],
    hints: [
      "在人群低患病率时，即使特异度很高，假阳性人数也可能超过真阳性。",
      "区分筛查与确诊；阳性后是否有可靠、可接受的复核检查和有效治疗？",
      "权衡早诊收益、焦虑与侵入性检查伤害、成本、公平性，并考虑先在高风险人群试点。",
    ],
    modelAnswer: "Early detection alone does not justify population screening. I would combine sensitivity and specificity with disease prevalence to calculate positive predictive value; in a low-prevalence population, many positive results may be false even when the test looks accurate. I would ask whether earlier treatment improves meaningful outcomes, whether there is a safe confirmatory pathway, and whether overdiagnosis identifies disease that would never cause harm. Benefits must be weighed against anxiety, invasive follow-up, cost and unequal access. A reasonable next step may be a controlled programme in a defined high-risk group with outcome monitoring rather than immediate universal screening.",
    rubricKeywords: ["prevalence", "false positive", "sensitivity", "specificity", "predictive", "overdiagnosis", "harm"],
    followUp: "How would lowering the test threshold change sensitivity and specificity?",
  },
  {
    id: "med-mock-oxygen",
    subject: "medicine",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "A patient has normal blood oxygen content at rest but becomes breathless during exercise. What mechanisms might explain this?",
    zhGuide: "不要锁定单一诊断；从供氧链条逐段分析并提出可区分机制的检测。",
    anchors: ["Gas exchange", "Cardiac output", "Respiration"],
    hints: [
      "组织供氧取决于动脉血氧含量与心输出量，而不是只有静息血氧饱和度。",
      "运动时可能暴露通气、弥散、循环、血红蛋白或肌肉代谢的储备不足。",
      "说明你会比较哪些数据：运动血氧、心率、肺功能、血红蛋白、ECG 或心肺运动试验。",
    ],
    modelAnswer: "Normal resting oxygen content does not show that the whole oxygen-delivery system has adequate reserve. During exercise, demand rises and limitation could occur in ventilation, diffusion across the lung, cardiac output, haemoglobin concentration, peripheral blood flow or muscle metabolism. Anxiety or deconditioning may also increase breathlessness without arterial desaturation. I would ask about timing and associated symptoms, then compare exercise oxygen saturation, heart rate and blood pressure, spirometry, haemoglobin and ECG; a cardiopulmonary exercise test could separate ventilatory from circulatory limitation. I would keep the response mechanistic and differential rather than claiming a diagnosis from one observation.",
    rubricKeywords: ["cardiac output", "haemoglobin", "diffusion", "ventilation", "exercise", "test", "differential"],
    followUp: "Why can severe anaemia coexist with a normal oxygen saturation reading?",
  },
  {
    id: "econ-past-holiday",
    subject: "economics",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "牛剑面试—经济和经管 / Oxford sample",
    difficulty: "Stretch",
    question: "Alex gains daily utility proportional to √x from spending x euros and has €400 for four days. How should he allocate it, and what changes if Brian overweights today's spending?",
    zhGuide: "从边际效用递减推导平滑消费，再分析现时偏好导致的时间不一致。",
    anchors: ["Utility", "Marginal analysis", "Behavioural economics"],
    hints: [
      "√x 是凹函数：随着 x 增加，额外一欧元带来的边际效用如何变化？",
      "若四天权重相同，把一欧元从高消费日移到低消费日会怎样影响总效用？",
      "Brian 每天都偏爱“今天”，会不断提前消费；这与储蓄、养老金或承诺装置有什么联系？",
    ],
    modelAnswer: "Because √x is concave, marginal utility falls as daily spending rises. With equal weights across days, Alex maximises total utility by smoothing consumption at €100 per day; moving money from a higher-spending day to a lower-spending day raises total utility until marginal utilities are equal. Brian's extra weight on the present creates present bias. Each day he plans to be patient later but spends too much when later becomes today, producing time-inconsistent choices and a front-loaded path. A commitment device such as daily budgets or pre-paid restrictions could improve his welfare. The policy analogy is automatic pension enrolment or commitment savings.",
    rubricKeywords: ["concave", "marginal utility", "smooth", "present bias", "time inconsistent", "commitment"],
    followUp: "Would equal spending remain optimal if prices differed across the four days?",
  },
  {
    id: "econ-past-bankers",
    subject: "economics",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "牛剑面试—经济和经管 / Oxford sample",
    difficulty: "Core",
    question: "Do bankers deserve the pay they receive, and should government limit it?",
    zhGuide: "把“公平不公平”的直觉改写为竞争、稀缺技能、租金、激励和外部性问题。",
    anchors: ["Labour markets", "Market power", "Government intervention"],
    hints: [
      "先建立竞争市场解释：工资可能反映边际产出和稀缺技能。",
      "再质疑假设：超额利润、有限竞争、隐性担保或短期奖金是否产生经济租金和扭曲激励？",
      "比较薪资上限、累进税、竞争政策、资本要求和奖金递延的目标与副作用。",
    ],
    modelAnswer: "If banking labour markets were competitive, very high pay could reflect scarce skills and high marginal productivity, making a direct cap difficult to justify. But that conclusion depends on assumptions. Market concentration, economic rents, implicit public guarantees and compensation tied to short-term gains can raise pay without equivalent social value and encourage excessive risk whose costs fall on others. I would target the mechanism rather than the headline number: stronger competition, capital and clawback rules, deferred bonuses, and progressive taxation may address rents, incentives and equity more precisely than a universal cap. Evidence on productivity, mobility and risk-taking would determine which account is stronger.",
    rubricKeywords: ["competitive", "productivity", "rent", "market power", "risk", "externality", "policy"],
    followUp: "How could we test whether high pay reflects talent or economic rent?",
  },
  {
    id: "econ-mock-tickets",
    subject: "economics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "Popular concert tickets sell out in seconds and then trade at much higher prices. Is the original ticket price too low?",
    zhGuide: "区分市场出清价格与主办方目标；低价可能是错误，也可能是有意的策略。",
    anchors: ["Supply and demand", "Price discrimination", "Market design"],
    hints: [
      "固定场馆容量意味着短期供给近乎垂直；瞬间售罄说明在该价格下超额需求。",
      "但主办方可能重视公平、粉丝关系、周边消费和长期声誉，而非只最大化票房。",
      "黄牛市场揭示支付意愿，也存在机器人抢票、信息不对称和租金转移；比较实名制、动态定价与抽签。",
    ],
    modelAnswer: "In a narrow market-clearing sense, an immediate sell-out and a high resale price suggest the face value is below equilibrium. But too low depends on the organiser's objective. A lower price may broaden access, reward fans, build reputation or increase complementary spending, while scarcity transfers rents to resellers. The secondary price is also imperfect evidence because bots, speculation and thin trading can distort it. I would compare dynamic pricing, verified resale with capped mark-ups, identity checks and lotteries. Each allocates tickets by willingness to pay, timing or chance, so the choice is partly about efficiency, distribution and enforcement rather than a single correct price.",
    rubricKeywords: ["supply", "demand", "equilibrium", "resale", "rent", "dynamic pricing", "fairness"],
    followUp: "Would an auction be more efficient, and would it necessarily be fairer?",
  },
  {
    id: "econ-mock-cleaners",
    subject: "economics",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "A school rewards cleaners only by the number of rooms completed. What behaviour might the metric create?",
    zhGuide: "使用激励设计和多任务委托问题：可测指标不一定等于真正目标。",
    anchors: ["Incentives", "Principal-agent problem", "Measurement"],
    hints: [
      "学校真正关心的是哪些结果？速度只是其中之一，还包括质量、安全和隐蔽任务。",
      "当奖励只绑定一个可测指标，员工会合理地把努力转向它，可能牺牲未被计量的工作。",
      "设计更好的制度：混合质量抽查、团队反馈、合理自主性与申诉，同时防止指标过多。",
    ],
    modelAnswer: "The measure may improve speed, but it can also become the target rather than a proxy for good cleaning. Workers may rush visible rooms, avoid difficult areas, underreport problems or neglect safety and maintenance that are harder to count. This is a multi-task principal-agent problem: rewarding the measurable task changes the allocation of effort across all tasks. I would use a balanced system combining workload-adjusted output, random quality checks, safety indicators and qualitative feedback, while giving staff discretion over methods. The design should be tested for gaming and worker burden because adding more metrics can create a new form of distortion.",
    rubricKeywords: ["incentive", "metric", "proxy", "quality", "gaming", "principal", "multi-task"],
    followUp: "Could removing performance metrics entirely produce a different agency problem?",
  },
  {
    id: "ppe-past-flight",
    subject: "ppe",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Stretch",
    question: "The plane will fly whether or not I buy a ticket, so I have no moral reason not to fly. Is that argument convincing?",
    zhGuide: "暂时接受航空造成气候损害这一前提，分析个体在集体行动中的责任。",
    anchors: ["Moral reasoning", "Collective action", "Counterexamples"],
    hints: [
      "区分单次行为的边际因果影响与参与一种集体实践的责任。",
      "用投票、排队或许多人各造成微小伤害的例子检验“我不改变结果就无责任”。",
      "考虑阈值效应、需求信号、规则可普遍化、象征/政治影响以及行动成本。",
    ],
    modelAnswer: "The argument identifies a real issue: one passenger rarely determines whether a particular flight departs. But moral reasons need not require being individually decisive. Ticket purchases contribute probabilistically to future scheduling and form part of an aggregate demand that causes harm. A principle permitting everyone to ignore tiny contributions would undermine many collective goods, as with voting or pollution. There may also be reasons of fairness: benefiting from a harmful practice while relying on others to restrain themselves. Still, the strength of the reason depends on alternatives, necessity and cost. I would distinguish having some moral reason not to fly from claiming an absolute prohibition.",
    rubricKeywords: ["collective", "marginal", "demand", "fairness", "universal", "reason", "absolute"],
    followUp: "Does buying a carbon offset remove the moral reason not to fly?",
  },
  {
    id: "ppe-past-blame",
    subject: "ppe",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "What exactly is involved in blaming someone?",
    zhGuide: "从一个简单定义开始，用反例不断修正，而不是罗列情绪词。",
    anchors: ["Conceptual analysis", "Counterexamples", "Moral responsibility"],
    hints: [
      "尝试定义：责备是否只是相信某人做错了？找一个相信对方做错但并不责备的例子。",
      "责备是否必然包含愤怒、谴责、关系期待或要求对方说明理由？",
      "区分一个人应受责备与我们实际上责备他；再考虑无知、强迫和能力如何影响责任。",
    ],
    modelAnswer: "Blame seems to involve more than judging that an action was wrong. I may think a stranger made a mistake without adopting any blaming attitude. Blame often includes holding the agent responsible: treating the action as expressing poor regard or judgment, feeling resentment or indignation, and seeing an apology or justification as appropriate. Yet emotion cannot be essential because someone may blame calmly. I would therefore describe blame as a responsibility-directed stance that changes how we regard or respond to a person. Its justification depends on agency, knowledge, control and reasonable expectations, which explains why coercion or excusable ignorance can reduce blame.",
    rubricKeywords: ["wrong", "responsible", "attitude", "counterexample", "agency", "knowledge", "control"],
    followUp: "Can it ever be morally wrong to blame someone who is blameworthy?",
  },
  {
    id: "ppe-mock-free-speech",
    subject: "ppe",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "Should a university protect speech that many students find deeply offensive?",
    zhGuide: "先区分冒犯、伤害、骚扰和威胁，再权衡求真、平等参与与制度职责。",
    anchors: ["Liberty", "Harm principle", "Institutional design"],
    hints: [
      "“offensive”范围太宽；哪些言论只是观点，哪些构成针对性骚扰、威胁或排除？",
      "保护表达的理由包括纠错、学术探究和防止权力压制；限制的理由包括安全与平等参与。",
      "比较内容禁令、时间地点方式规则、反驳、支持服务和明确反骚扰标准。",
    ],
    modelAnswer: "A university has strong reasons to protect even offensive ideas because inquiry requires the possibility of error, challenge and dissent. But offence is not the only relevant category. Targeted harassment, credible threats or conduct that systematically prevents others from participating can undermine the same educational mission that free speech serves. I would therefore resist a broad ban based on subjective offence and instead use viewpoint-neutral rules focused on conduct, time, place and manner, alongside opportunities for rebuttal and support. Hard cases turn on definitions and evidence: the institution should explain why a restriction is necessary, proportionate and consistently applied.",
    rubricKeywords: ["offence", "harm", "harassment", "inquiry", "participation", "proportionate", "viewpoint"],
    followUp: "Who should decide where offence ends and harassment begins?",
  },
  {
    id: "ppe-mock-vote",
    subject: "ppe",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "If one vote almost never changes an election result, why vote?",
    zhGuide: "不要只回答“公民责任”；比较工具性、表达性、规则公平与集体行动理由。",
    anchors: ["Rational choice", "Collective action", "Political obligation"],
    hints: [
      "工具性期望收益可写成改变结果的概率乘以结果价值，再减去投票成本。",
      "投票还可能表达身份、支持合法性、提供信息，或履行公平参与的义务。",
      "检验这些理由是否会要求人投任何票，还是要求成为知情选民；考虑弃权是否也能表达立场。",
    ],
    modelAnswer: "If voting is assessed only by the chance of being pivotal, the expected instrumental benefit is often tiny. Yet elections are collective practices whose legitimacy and accuracy depend on widespread participation. A voter may have a fairness-based reason not to free-ride on others, an expressive reason to endorse a position, or a reason to contribute information about public preferences. These arguments do not make every vote obligatory: the cost of becoming informed, available options and conscientious abstention matter. I would conclude that the near-zero pivotal probability weakens one argument for voting, but it does not exhaust the kinds of reasons citizens can have.",
    rubricKeywords: ["pivotal", "expected", "collective", "free ride", "expressive", "legitimacy", "abstain"],
    followUp: "Would compulsory voting strengthen or weaken democratic legitimacy?",
  },
  {
    id: "law-past-car",
    subject: "law",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "What does it mean to take another person's car?",
    zhGuide: "先提出定义，再用边界案例测试并修正：是否必须移动、控制、永久占有或剥夺使用？",
    anchors: ["Definition", "Application", "Counterexamples"],
    hints: [
      "从一个初始规则开始，例如未经同意取得控制并剥夺车主使用。",
      "下雨时在未上锁的车里坐 15 分钟但不移动它，算“take”吗？你的定义如何处理？",
      "比较移动、控制、使用、意图和持续时间；法律规则需要清晰，也要覆盖真正的危害。",
    ],
    modelAnswer: "I would begin with a provisional definition: taking involves assuming unauthorised control over another's car in a way that interferes with the owner's possession or use. Physical movement is strong evidence but may not be necessary; sitting in an unlocked car temporarily exercises control and excludes the owner, though it differs from driving away. Permanent deprivation may be required for theft but not for every offence involving unauthorised use. I would therefore ask what purpose the legal rule serves and distinguish possession, use and ownership. Testing the definition against short occupation, borrowing, towing and mistaken belief would reveal where intention and duration should matter.",
    rubricKeywords: ["define", "control", "consent", "possession", "deprive", "intention", "counterexample"],
    followUp: "Would remotely disabling the car without entering it count as taking?",
  },
  {
    id: "law-past-redlight",
    subject: "law",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "Should it be illegal to run a red light in the middle of the night on an empty road?",
    zhGuide: "区分具体行为是否造成伤害与普遍规则如何提供可预测性并控制判断误差。",
    anchors: ["Rule design", "Harm", "Legal certainty"],
    hints: [
      "支持例外：若确实无人且无伤害，惩罚是否缺乏比例性？",
      "反对例外：谁判断道路“空”？错误判断、执法证明和行为可预测性会怎样？",
      "比较绝对规则、紧急情况抗辩、感应式信号灯和酌情处罚。",
    ],
    modelAnswer: "The isolated act may appear harmless, but law also coordinates expectations and manages imperfect judgment. A driver can be wrong about whether the road is empty, and a general exception based on personal assessment would reduce predictability and be difficult to enforce consistently. That supports a clear prohibition. However, legality and punishment need not be all-or-nothing: genuine emergencies may justify a defence, and penalties should be proportionate. Technology such as sensor-controlled lights can reduce needless waiting without making safety depend on each driver's confidence. I would therefore retain the rule while allowing narrowly defined exceptions and sensible enforcement.",
    rubricKeywords: ["harm", "predictability", "judgment", "enforce", "proportionate", "exception", "rule"],
    followUp: "Is the fact that an act is illegal itself a moral reason not to do it?",
  },
  {
    id: "law-mock-height",
    subject: "law",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "A fire service excludes every applicant below 170 cm. Is the rule fair?",
    zhGuide: "从合法目标、规则与目标的关联、替代方案和间接歧视进行分析。",
    anchors: ["Equality", "Proportionality", "Evidence"],
    hints: [
      "先问身高门槛追求什么目标：力量、伸展距离、装备适配还是安全？",
      "固定门槛可能对某些群体产生不成比例影响，但这是否由工作必要性客观证明？",
      "能否用直接的体能、任务模拟或可调装备更精准地测试真实能力？",
    ],
    modelAnswer: "The service has a legitimate aim in ensuring firefighters can perform safely, but fairness depends on whether height is a necessary and proportionate proxy for that ability. A fixed threshold may exclude capable applicants and disproportionately affect groups with lower average height, creating indirect discrimination. I would ask for evidence linking 170 cm to essential tasks and whether less exclusionary alternatives exist, such as job-specific strength, reach and equipment tests. If direct testing predicts performance better, the blanket rule is difficult to justify. Equal treatment is not merely applying one rule to everyone; the rule itself must be relevant and evidence-based.",
    rubricKeywords: ["legitimate", "proxy", "proportionate", "indirect", "evidence", "alternative", "task"],
    followUp: "Could individual testing itself introduce a different kind of unfairness?",
  },
  {
    id: "law-mock-ai-judge",
    subject: "law",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "Should judges use an algorithm that predicts a defendant's risk of reoffending?",
    zhGuide: "区分辅助决策与替代决策，并分析准确性、解释权、偏见、个体化和正当程序。",
    anchors: ["Rule of law", "Evidence", "Procedural fairness"],
    hints: [
      "预测可能提高一致性，但训练数据反映过去制度；准确率应与什么基准比较？",
      "群体统计是否能公平决定个体自由？被告能否理解和质疑模型输入与推理？",
      "设计约束：公开验证、禁止敏感代理变量、人工理由、申诉、持续审计和用途限制。",
    ],
    modelAnswer: "A validated model might make risk evidence more consistent than unaided intuition, but it should not become an unchallengeable decision-maker. Historical data can encode unequal policing, group accuracy can conceal unequal errors, and a statistical association does not fully capture an individual's circumstances. Procedural fairness requires the defendant to know the material basis of a decision and contest errors. I would permit carefully limited advisory use only with independent validation, published performance across groups, explainable inputs, human reasons and appeal. The weight given to the score should also depend on the decision: restricting liberty demands stronger safeguards than allocating voluntary support.",
    rubricKeywords: ["consistent", "bias", "individual", "explain", "contest", "audit", "human"],
    followUp: "Is an opaque but more accurate model preferable to a transparent but less accurate one?",
  },
  {
    id: "english-past-children",
    subject: "english",
    sourceMode: "past",
    origin: "Oxford sample question",
    sourceTitle: "2025年最新版牛津大学面试例题",
    difficulty: "Core",
    question: "In what ways is writing for children different from writing for adults?",
    zhGuide: "质疑二分法本身，并从叙述声音、读者预设、形式和出版分类分析具体文本效果。",
    anchors: ["Audience", "Narrative voice", "Form"],
    hints: [
      "“儿童”与“成人”都不是单一读者群；年龄、阅读能力和文化经验如何改变预设？",
      "比较词汇并不够，考虑叙述视角、信息隐藏、道德框架、插图和双重受众。",
      "找反例：有些儿童文学复杂而成人类型小说高度公式化；标签可能由市场而非文本决定。",
    ],
    modelAnswer: "The distinction is useful but unstable because neither children nor adults form a single audience. Writing for younger readers may manage vocabulary, exposition and danger differently, and it often uses child focalisation, illustration or an adult-child double address. Yet simplicity of language need not mean simplicity of theme; children's literature can handle grief, power or identity through metaphor and narrative distance. Conversely, adult genre fiction may be highly conventional. I would therefore analyse how a text imagines its reader through voice, form, withheld knowledge and moral agency, while recognising that publishing categories and changing readers also help create the boundary.",
    rubricKeywords: ["audience", "voice", "focalisation", "form", "theme", "category", "reader"],
    followUp: "Can a text's intended audience change without the text itself changing?",
  },
  {
    id: "english-past-silence",
    subject: "english",
    sourceMode: "past",
    origin: "Reported Oxbridge question",
    sourceTitle: "牛剑18个学科900道面试题",
    difficulty: "Stretch",
    question: "Can we hear silence?",
    zhGuide: "把抽象问题带回语言与文学：沉默是物理上的无声、被感知的间隙，还是具有意义的修辞行为？",
    anchors: ["Close reading", "Semantics", "Form"],
    hints: [
      "区分缺少声音与意识到声音停止；后者可能依赖前后对比。",
      "在对话、戏剧和诗歌中，停顿、空白、标点如何让沉默变得可感知？",
      "沉默也可能是拒绝、服从、创伤或权力。意义来自语境，而非沉默本身发声。",
    ],
    modelAnswer: "Physically, silence is the absence or near-absence of audible sound, so it seems impossible to hear it as an object. Yet we can perceive a cessation: the sudden gap after music or speech becomes salient because of contrast and expectation. Literature makes this paradox productive. A pause in drama, a blank space on a page or an unanswered question can be experienced as meaningful silence, shaped by what surrounds it. Silence may signal refusal, fear, intimacy or exclusion, but the same pause can mean differently in another context. We do not hear silence speaking; we interpret an absence through form and expectation.",
    rubricKeywords: ["absence", "contrast", "pause", "context", "form", "interpret", "meaning"],
    followUp: "How could a novelist represent silence differently from a playwright?",
  },
  {
    id: "english-mock-unreliable",
    subject: "english",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Core",
    question: "If a narrator tells us they are unreliable, should we believe them?",
    zhGuide: "分析自我指涉悖论，并区分叙述者的事实可靠性、解释可靠性和道德可靠性。",
    anchors: ["Narration", "Irony", "Reader response"],
    hints: [
      "若相信“我不可靠”，似乎至少相信了这一句话；但承认局限可能反而增加可信度。",
      "不可靠可以指记忆错误、故意欺骗、认知受限或价值判断偏差。",
      "文本可通过其他人物、重复矛盾、语气和戏剧反讽让读者建立第二层判断。",
    ],
    modelAnswer: "The statement creates a productive tension rather than a simple logical trap. Admitting unreliability may itself be evidence of self-awareness, but it does not tell us which claims are false or why. I would distinguish factual unreliability from limited interpretation and moral distortion. A narrator may report events accurately while misunderstanding them, or lie while accidentally revealing a truth about their motives. Readers therefore compare the voice with patterns the text provides: contradictions, other perspectives, tonal irony and gaps between action and explanation. The question shifts authority from the speaker alone to the relation between narrator, textual form and reader.",
    rubricKeywords: ["self-aware", "factual", "interpretation", "contradiction", "irony", "reader", "authority"],
    followUp: "Can a third-person narrator be unreliable in the same way?",
  },
  {
    id: "english-mock-translation",
    subject: "english",
    sourceMode: "mock",
    origin: "Perfect Oxbridge original",
    sourceTitle: "Perfect Oxbridge Interview 自研题",
    difficulty: "Stretch",
    question: "Is a translation a new literary work?",
    zhGuide: "避免非此即彼；从语义、声音、文化语境、作者性和读者经验讨论“相同”与“新”。",
    anchors: ["Language", "Form", "Authorship"],
    hints: [
      "逐字对应常无法保存节奏、双关、语域和文化联想，译者必须做形式选择。",
      "但译者并非完全自由：原作对意义、结构和人物仍施加约束。",
      "比较多个同一作品译本；它们共同指向原作，却为新读者创造不同审美对象。",
    ],
    modelAnswer: "A translation is derivative and creative at once. It remains accountable to a prior work, but no language offers a neutral one-to-one transfer of rhythm, register, ambiguity and cultural association. The translator must choose which effects to preserve and which losses to compensate elsewhere, so different translations can produce distinct voices and interpretations. Calling it wholly new would obscure that obligation; calling it merely the same work would hide the translator's authorship. I would describe translation as a new linguistic and literary realisation of an existing work, whose success depends on its aims, audience and explanation of unavoidable choices.",
    rubricKeywords: ["language", "rhythm", "choice", "translator", "original", "new", "audience"],
    followUp: "Could a deliberately unfaithful translation ever be the more faithful literary version?",
  },
];

export const QUESTION_BANK: InterviewQuestion[] = [
  ...CORE_QUESTION_BANK,
  ...ADDITIONAL_QUESTIONS,
];

export const sourceModeLabel: Record<SourceMode, string> = {
  past: "牛剑真题 / 官方例题",
  mock: "Perfect 自研模拟题",
};

export function subjectById(id: SubjectId) {
  return SUBJECTS.find((subject) => subject.id === id) ?? SUBJECTS[0];
}
